### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nhathoang0110** [Ascend-Research/HeadPoseEstimation-WHENet#1]
This is my error. Can you help me ?
" Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    model = WHENet('WHENet.h5')
  File "/home/hoangnn/pose/HeadPoseEstimation-WHENet/whenet.py", line 13, in __init__
    out = keras.layers.GlobalAveragePooling2D()(out)
  File "/home/hoangnn/.local/lib/python3.7/site-packages/keras/engine/topology.py", line 606, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/home/hoangnn/.local/lib/python3.7/site-packages/keras/engine/topology.py", line 2845, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'"

**Comment by yijunzhou-huawei** [comment]
Hi there, can you provide more details about the error?

**Comment by saadnajib** [comment]
> This is my error. Can you help me ? " Traceback (most recent call last): File "demo.py", line 21, in model = WHENet('WHENet.h5') File "/home/hoangnn/pose/HeadPoseEstimation-WHENet/whenet.py", line 13, in **init** out = keras.layers.GlobalAveragePooling2D()(out) File "/home/hoangnn/.local/lib/python3.7/site-packages/keras/engine/topology.py", line 606, in **call** previous_mask = _collect_previous_mask(inputs) File "/home/hoangnn/.local/lib/python3.7/site-packages/keras/engine/topology.py", line 2845, in _collect_previous_mask mask = node.output_masks[tensor_index] AttributeError: 'Node' object has no attribute 'output_masks'"

Change 
import keras
To
import tensorflow.keras as keras
in Whenet.py
