### ISSUE TITLE
Error in runing demo_video.py 

### ISSUE THREAD

**Issue by zwt233** [Ascend-Research/HeadPoseEstimation-WHENet#28]
Hi I am runing the demo_video.py, and get the following error:

```
Traceback (most recent call last):
  File "demo_video.py", line 81, in <module>
    main(args)
  File "demo_video.py", line 54, in main
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.8) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
Can you help me ? Thanks a lot!

**Comment by GorokhovaPolina** [comment]
Hello! In case of being still actual...
This mistake occurs because of incorrect video feed. the last frame is empty.
To avoid this in demo_video.py in main function right after case of exception:
```
except:
    break
```
add next lines:
```
if not ret or frame is None:
    print("Warning: Empty frame received or stream ended. Skipping...")
    break
```
